apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eks-cluster-${{values.name}}
  description: Stateful Workload for ${{ values.name }}
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argo-workflows.cnoe.io/label-selector: env=dev,entity-id=${{values.name}}
    argo-workflows.cnoe.io/cluster-name: local
spec:
  type: kubernetes-cluster
  lifecycle: experimental
  owner: guest
  system: ${{values.name | dump}}
