apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: "eks-cluster-${{values.name}}-git-repository"
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interval: 30s
  url: https://github.com/awslabs/data-on-eks.git
  ref:
    branch: main