apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates a EKS cluster with JupyterHub + extra enabled through Terraform
  name: jupyterhub-on-eks
  title: Create Data on EKS - JupyterHub
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        tfVars:
          properties:
            acm_certificate_domain:
              default: ""
              description: Enter domain name with wildcard and ensure ACM certificate is created for this domain name, e.g. *.example.com
              type: string
            cognito_custom_domain:
              default: eks
              description: Cognito domain prefix for Hosted UI authentication endpoints
              type: string
            eks_cluster_version:
              default: "1.29"
              description: EKS Cluster version
              type: string
            jupyter_hub_auth_mechanism:
              default: dummy
              description: 'Allowed values: cognito, dummy'
              type: string
            jupyterhub_domain:
              default: ""
              description: Enter sub-domain name for jupyterhub to be hosted,  e.g. eks.example.com. Only needed if auth mechanism is set to cognito
              type: string
            name:
              default: jupyterhub-on-eks
              description: Name of the VPC and EKS Cluster
              type: string
            region:
              default: us-west-2
              description: Region
              type: string
            secondary_cidr_blocks:
              default:
                - 100.64.0.0/16
              description: Secondary CIDR blocks to be attached to VPC
              items:
                type: string
              type: array
            vpc_cidr:
              default: 10.1.0.0/21
              description: VPC CIDR. This should be a valid private (RFC 1918) CIDR range
              type: string
          title: Terraform variables
          type: object
        adminRoleName:
          default: Admin
          description: Name of the role to give the administrative rights on the EKS cluster.
          title: Admin Role Name
          type: string       
        name:
          title: name of this entry
          type: string
        namespace:
          default: flux-system
          title: namespace within the kubernetes cluster to deploy this
          type: string
      title: Configuration Options
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates-jupyterhub/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          tfVars: ${{ parameters.tfVars }}
          adminRoleName: ${{parameters.adminRoleName}}
          clusterName: ${{ parameters.clusterName }}
    - id: publish
      name: Publishing to a gitea git repository
      action: publish:gitea
      input:
        description: Example JupyterHub demo
        # Hard coded value for this demo purposes only.
        repoUrl: cnoe.localtest.me:8443/gitea?repo=${{parameters.name}}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        # necessary until we generate our own cert
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
